-- A model of how the databse was created in ElephantSQL

CREATE TABLE riddles (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	rtext TEXT,
	rsolution TEXT
)


INSERT INTO riddles (rtext, rsolution) 
VALUES
('When I blink my eyes, you do as you are told.','Traffic lights'),
('I am often brough to the table but never eaten.','Pack of cards'),
('I am served a lot but never eaten.','Tennis ball'),
('My legs only touch the ground when I am not moving.','Wheelbarrow'),
('I am a tree that grows downwards.','Family tree'),
('I belong to you, but others use me more than you.','[Your] name'),
('I am white when I am dirty and black when I am clean.','Chalkboard'),
('I am that place where today comes before yesterday.','Dictionary'),
('I live in the water but I never get wet.','Reflection'),
('I come in through no door, and vanish just the same.','Reflection'),
('“Here! Here!” I keep saying, but I have no eyes to see.','Forefinger'),
('You answer me although I never asked anything.','Telephone'),
('I carry the flesh of the dead but seek the flesh of the living.','Fish hook'),
('I have two bodies joined in one. The stiller I stand, the faster I run.','Hourglass'),
('I never was, but always will be. No one ever saw me, yet my existence is undisputed.','Tomorrow'),
('I have roots that no one sees, I am taller than all, but hardly ever grow.','Mountain'),
('I have keys and a lock but no door. I have space but no room. I have an end but no beginning. You can enter but you can’t go inside.','Keyboard'),
('I have six legs, two heads, and two hands, yet I only use for legs wherever I go.','Horseman'),
('I am a father’s and a mother’s child, but no one’s son.','Daughter'),
('I divide by uniting and unite by dividing.','Scissors'),
('I can’t be felt, I can’t be seen, I fill the empty holes.','Darkness'),
('I jump when walking and sit when standing.','Kangaroo'),
('I am large as a mountain, small as a pea, endlessly swimming in a waterless sea.','Asteroid'),
('I have many wheels but I never move.','Car park'),
('I am easy to lift but hard to throw.','Feather'),
('Poor people have plenty of me. Rich people need me. If you eat me, you will die.','Nothing'),
('I die when you say my name.','Silence'),
('No one wants me, yet no one wants to lose me.','Lawsuit'),
('I am a frame displaying infinite pictures.','Glasses'),
('I am made of wood but cannot be cut by the strongest saw.','Sawdust'),
('I am very easy to get into, but hard to get out of.','Trouble'),
('If there are three of me, there’s three. If there are two, there are two. If there is one of me, there are none.','Choices'),
('I go through doors but never come in or go out.','Keyhole'),
('I look younger the older you get.','Picture'),
('My rain dries all the ground it touches.','Volcano'),
('I only point in one direction, yet people trust me to find their way.','Compass'),
('I lose my head in the morning and I get it back at night.','Pillow'),
('The person who makes me and the person who buys me have no use for me. The person who uses me couldn’t care less about me.','Coffin'),
('I raise the dead and reverse time. I am an instant that lasts a lifetime.','Memory'),
('I am that part of you that gets seen more when it’s cold than when it’s hot.','Breath'),
('I am full of holes, but still hold water.','Sponge'),
('I am always in front of you but you cannot see me.','Future'),
('I dance to the music, although I can’t hear. Even when I stand still you cannot run away from me.','Shadow'),
('I am two lips that cannot speak.','Tulips'),
('I live under a shed but I am always wet.','Tongue'),
('Enlightened those that come to me, though wisdom I posses not. They say I’m wicked, but I have never caused offense to no one.','Candle'),
('I am light as a feather, yet not even the strongest can hold me for long.','Breath'),
('I can be as big as mountains, yet I weigh nothing.','Shadow'),
('I taste better than I smell.','Tongue'),
('I am harder to catch the faster you run.','Breath'),
('Flat as a leaf, round as a ring, I have two eyes, can’t see a thing.','Button'),
('I bring light to those who come to me, and give my life for them. But still they say I’m wicked.','Candle'),
('I am the part of the bird that’s not in the sky. I can swim in the ocean yet I remain dry.','Shadow'),
('I improve whenever I am broken.','Record'),
('If you let me live, I will soon die. Kill me, and I shall live long.','Candle'),
('The shorter I am, the bigger I get.','Temper'),
('I am in a most peculiar situation: I am often returned, although I am never borrowed.','Thanks'),
('I can hardly be weighed, I cannot be measured with outstretched hands, and I am carried by five.','Needle'),
('When you need me, you throw me away.','Anchor'),
('I live where there is light, but light kills me.','Shadow'),
('I have no feet, no hands, no wings, but easily I soar into the sky.','Smoke'),
('I am a grain of rice that fills the whole house.','Light'),
('I have no end, beginning, or middle.','Donut'),
('I am made longer by being cut at both ends.','Ditch'),
('I have a hundred legs, but cannot stand. I have a long neck, but no head.','Broom'),
('I get wetter the more I dry.','Towel'),
('I fall time and again, but never break.','Night'),
('I have many keys, and although I cannot open a single door, I can open hearts.','Piano'),
('I have a neck, but no head. Two arms, but no hands.','Shirt'),
('I am that which has been tomorrow and will be yesterday.','Today'),
('When I take five and add six, I get eleven. But when I take six and add seven, I get one.','Clock'),
('I am gentle enough to soothe your skin, light enough to fly in the sky, and strong enough to crack rocks.','Water'),
('You can swallow me, but I can swallow you just as easily.','Water'),
('When I move, my body stands still. When I stand still, I lie.','Clock'),
('I travel around the world but sit in one spot.','Stamp'),
('Chop me as you like, I will heal at once.','Water'),
('I can run, but cannot walk, I have a mouth but never talk, I have a bed but I never sleep.','River'),
('I can be broken without being touched or seen.','Heart'),
('I am often brough to the table but never eaten.','Plate'),
('I speak continuously and you can’t understand me. But look at my face, and you’ll know what I’m saying.','Clock'),
('I grow up and down at the same time.','Goose'),
('I get sharper the more I am used.','Brain'),
('I run with no feet and I roar with no mouth.','Wave'),
('When lights shines I cannot be seen. When light is taken away, I become visible.','Star'),
('I’m sad as I can be. No heart rejoices at my birth, and with a breath I die.','Sigh'),
('Here I come, yet you cannot see me.','Wind'),
('I’m like the letter O, that becomes a C, and like the letter C, that becomes an O.','Moon'),
('I am the size of a penny and have the power to move oceans.','Moon'),
('I have a head, but no body. I have a tail, but no legs.','Coin'),
('We clap and clap, but nobody hears us. When one of us dies, it cannot be buried while the other is alive.','Eyes'),
('You cannot keep me until you have given me.','Word'),
('You can touch me but cannot not see me.','Back'),
('I have three feet but no arms or legs.','Yard'),
('I have a tongue but cannot taste. I have a soul but cannot feel.','Shoe'),
('I am the least valuable thing you can have in your pocket.','Hole'),
('I can be cracked, I can be made, I can be told, I can be played.','Joke'),
('I get larger the more you take from me.','Hole'),
('I can run, but cannot walk. Wherever I go, thought follows close behind.','Nose'),
('I come without being called, and I am lost without being stolen.','Star'),
('You can walk on water with my power, but hold me in your hand, and I’ll vanish in the hour.','Ice'),
('When you stand up I disappear.','Lap'),
('I am that which you can mend with holes.','Net'),
('I have seas with no water, mountain with no stones and cities with no people.','Map'),
('I need to be broken before you can use me.','Egg'),
('What force or strength cannot accomplish, I perform with a single touch. Small I may be, but I can guard you like a lion.','Key'),
('I go up, but never down.','Age'),
('I get wetter the longer I stay in the sun.','Ice'),
('I am built once but made everyday.','Bed'),
('I am a well stocked pantry with no door to go in or our.','Nut'),
('I am that which ends everything.','G')
